// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onboardbase
{
    [OnboardbaseResourceType("onboardbase:index:secrets")]
    public partial class Secrets : Pulumi.ComponentResource
    {
        /// <summary>
        /// The secrets
        /// </summary>
        [Output("secrets")]
        public Output<string> Secrets { get; private set; } = null!;


        /// <summary>
        /// Create a Secrets resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Secrets(string name, SecretsArgs args, ComponentResourceOptions? options = null)
            : base("onboardbase:index:secrets", name, args ?? new SecretsArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class SecretsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// API Key for authorization
        /// </summary>
        [Input("apiKey", required: true)]
        public Input<string> ApiKey { get; set; } = null!;

        /// <summary>
        /// The environment to pull secrets from
        /// </summary>
        [Input("environment", required: true)]
        public Input<string> Environment { get; set; } = null!;

        /// <summary>
        /// The API Key passcode for encryption
        /// </summary>
        [Input("passcode", required: true)]
        public Input<string> Passcode { get; set; } = null!;

        /// <summary>
        /// The Project to pull secrets from
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public SecretsArgs()
        {
        }
    }
}
