// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onboardbase

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Secrets struct {
	pulumi.ResourceState

	// The secrets
	Secrets pulumi.StringOutput `pulumi:"secrets"`
}

// NewSecrets registers a new resource with the given unique name, arguments, and options.
func NewSecrets(ctx *pulumi.Context,
	name string, args *SecretsArgs, opts ...pulumi.ResourceOption) (*Secrets, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApiKey == nil {
		return nil, errors.New("invalid value for required argument 'ApiKey'")
	}
	if args.Environment == nil {
		return nil, errors.New("invalid value for required argument 'Environment'")
	}
	if args.Passcode == nil {
		return nil, errors.New("invalid value for required argument 'Passcode'")
	}
	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	var resource Secrets
	err := ctx.RegisterRemoteComponentResource("onboardbase:index:secrets", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type secretsArgs struct {
	// API Key for authorization
	ApiKey string `pulumi:"apiKey"`
	// The environment to pull secrets from
	Environment string `pulumi:"environment"`
	// The API Key passcode for encryption
	Passcode string `pulumi:"passcode"`
	// The Project to pull secrets from
	Project string `pulumi:"project"`
}

// The set of arguments for constructing a Secrets resource.
type SecretsArgs struct {
	// API Key for authorization
	ApiKey pulumi.StringInput
	// The environment to pull secrets from
	Environment pulumi.StringInput
	// The API Key passcode for encryption
	Passcode pulumi.StringInput
	// The Project to pull secrets from
	Project pulumi.StringInput
}

func (SecretsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*secretsArgs)(nil)).Elem()
}

type SecretsInput interface {
	pulumi.Input

	ToSecretsOutput() SecretsOutput
	ToSecretsOutputWithContext(ctx context.Context) SecretsOutput
}

func (*Secrets) ElementType() reflect.Type {
	return reflect.TypeOf((**Secrets)(nil)).Elem()
}

func (i *Secrets) ToSecretsOutput() SecretsOutput {
	return i.ToSecretsOutputWithContext(context.Background())
}

func (i *Secrets) ToSecretsOutputWithContext(ctx context.Context) SecretsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretsOutput)
}

// SecretsArrayInput is an input type that accepts SecretsArray and SecretsArrayOutput values.
// You can construct a concrete instance of `SecretsArrayInput` via:
//
//          SecretsArray{ SecretsArgs{...} }
type SecretsArrayInput interface {
	pulumi.Input

	ToSecretsArrayOutput() SecretsArrayOutput
	ToSecretsArrayOutputWithContext(context.Context) SecretsArrayOutput
}

type SecretsArray []SecretsInput

func (SecretsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Secrets)(nil)).Elem()
}

func (i SecretsArray) ToSecretsArrayOutput() SecretsArrayOutput {
	return i.ToSecretsArrayOutputWithContext(context.Background())
}

func (i SecretsArray) ToSecretsArrayOutputWithContext(ctx context.Context) SecretsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretsArrayOutput)
}

// SecretsMapInput is an input type that accepts SecretsMap and SecretsMapOutput values.
// You can construct a concrete instance of `SecretsMapInput` via:
//
//          SecretsMap{ "key": SecretsArgs{...} }
type SecretsMapInput interface {
	pulumi.Input

	ToSecretsMapOutput() SecretsMapOutput
	ToSecretsMapOutputWithContext(context.Context) SecretsMapOutput
}

type SecretsMap map[string]SecretsInput

func (SecretsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Secrets)(nil)).Elem()
}

func (i SecretsMap) ToSecretsMapOutput() SecretsMapOutput {
	return i.ToSecretsMapOutputWithContext(context.Background())
}

func (i SecretsMap) ToSecretsMapOutputWithContext(ctx context.Context) SecretsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretsMapOutput)
}

type SecretsOutput struct{ *pulumi.OutputState }

func (SecretsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Secrets)(nil)).Elem()
}

func (o SecretsOutput) ToSecretsOutput() SecretsOutput {
	return o
}

func (o SecretsOutput) ToSecretsOutputWithContext(ctx context.Context) SecretsOutput {
	return o
}

type SecretsArrayOutput struct{ *pulumi.OutputState }

func (SecretsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Secrets)(nil)).Elem()
}

func (o SecretsArrayOutput) ToSecretsArrayOutput() SecretsArrayOutput {
	return o
}

func (o SecretsArrayOutput) ToSecretsArrayOutputWithContext(ctx context.Context) SecretsArrayOutput {
	return o
}

func (o SecretsArrayOutput) Index(i pulumi.IntInput) SecretsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Secrets {
		return vs[0].([]*Secrets)[vs[1].(int)]
	}).(SecretsOutput)
}

type SecretsMapOutput struct{ *pulumi.OutputState }

func (SecretsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Secrets)(nil)).Elem()
}

func (o SecretsMapOutput) ToSecretsMapOutput() SecretsMapOutput {
	return o
}

func (o SecretsMapOutput) ToSecretsMapOutputWithContext(ctx context.Context) SecretsMapOutput {
	return o
}

func (o SecretsMapOutput) MapIndex(k pulumi.StringInput) SecretsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Secrets {
		return vs[0].(map[string]*Secrets)[vs[1].(string)]
	}).(SecretsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecretsInput)(nil)).Elem(), &Secrets{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecretsArrayInput)(nil)).Elem(), SecretsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecretsMapInput)(nil)).Elem(), SecretsMap{})
	pulumi.RegisterOutputType(SecretsOutput{})
	pulumi.RegisterOutputType(SecretsArrayOutput{})
	pulumi.RegisterOutputType(SecretsMapOutput{})
}
